//Get Pokemon
export const GET_POKEMON_LOADING = 'GET_POKEMON_LIST_LOADING'
export const GET_POKEMON_ERROR = 'GET_POKEMON_LIST_ERROR'

//Get Pokemon List
export const GET_POKEMON_LIST = 'GET_POKEMON_LIST'
export const GET_POKEMON_NEW_LIST = 'GET_POKEMON_NEW_LIST'

//Detalhes Pokemon
export const GET_DETALHES_POKEMON = 'GET_DETALHES_POKEMON'
export const URL_DETALHES_POKEMON = 'URL_DETALHES_POKEMON'
